[package]
name = "basic_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nject = "0.3.0"
rustle_core = { path = "../../packages/core" }
