[package]
name = "ngyn_macros"
version = "0.2.8"
edition = "2021"
description = "Modular backend framework for web applications"
license = "MIT"

[dependencies]
nject = "0.3.0"
syn = "2.0.29"
quote = "1.0.33"
ngyn_shared = { version = "0.3.0", path = "../shared" }

[lib]
path = "src/lib.rs"
proc-macro = true
