[package]
name = "ngyn_shared"
version = "0.3.0"
edition = "2021"
description = "Modular backend framework for web applications"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.74"
nject = "0.3.0"
