[package]
name = "ngyn_shared"
version = "0.3.1"
edition = "2021"
description = "Modular backend framework for web applications"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.74"
nject = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
url = "2.5.0"
